version: '3'

services:
  server:
    build:
      context: .
      dockerfile: ./server
    # expose: 
    #   - 8080
    # environment:
    #   API_HOST: http://localhost:3000/
    #   APP_SERVER_PORT: 8080
    ports:
      - 8080:8080
    # volumes:
    #   - .:/server
    command: npm run start

  client:
    build: 
      context: .
      dockerfile: ./client
    # expose: 
    #   - 3000
    # environment:
    #   - REACT_APP_PORT=3000
    ports:
      - 3000:3000
    # volumes:
    #   - .:/client
    # links: 
    #   - server
    command: npm run start